#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require_relative "../lib/marvi"

OptionParser.new do |opts|
  opts.banner = "Usage: marvi [FILE...]\n       cat FILE | marvi"
  opts.on("-h", "--help", "Show help") do
    puts opts
    exit
  end
  opts.on("-v", "--version", "Show version") do
    puts Marvi::VERSION
    exit
  end
end.parse!

ARGV.each do |file|
  abort "marvi: cannot open #{file}" unless File.file?(file) && File.readable?(file)
end

if $stdout.tty?
  if ARGV.empty?
    Marvi::Renderer::Curses.new.render($stdin.read)
  else
    Marvi::Renderer::Curses.new.render_files(ARGV)
  end
else
  renderer = Marvi::Renderer::ANSI.new
  if ARGV.empty?
    print renderer.render($stdin.read)
  else
    ARGV.each_with_index do |file, i|
      if ARGV.size > 1
        puts if i.positive?
        puts "==> #{file} <=="
      end
      print renderer.render(File.read(file, encoding: Encoding::UTF_8))
    end
  end
end
